In [2]:
import torch

In [3]:
# Some utils
randint  = torch.randint(-100, 100, (6, ))
print(randint)

arange = torch.arange(2, 6)
print(arange)

linspace = torch.linspace(0, 10, steps=5)
print(linspace)

logspace = torch.logspace(0.1, 10, steps=5)
print(logspace)

# diagonal matrix
eye = torch.eye(5)

print(eye)

tensor([-57, -38, -46, -97,  42,   2])
tensor([2, 3, 4, 5])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([1.2589e+00, 3.7584e+02, 1.1220e+05, 3.3497e+07, 1.0000e+10])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [4]:
%%time
zeros = torch.rand(3, 10, 25, 29, 100, 100)
# WITH CPU

CPU times: user 428 ms, sys: 40.7 ms, total: 469 ms
Wall time: 473 ms


In [5]:
%%time
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print(device)
zeros = torch.rand(3, 10, 25, 29, 100, 100, device=device)
# WITH GPU! 

mps
CPU times: user 20 ms, sys: 43.5 ms, total: 63.5 ms
Wall time: 64.1 ms


In [6]:
# More utils

# Probabilites
probabilities = torch.tensor([0.3, 0.3, 0.3])
samples  = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

# concat 
tensor = torch.tensor([1, 2])
out = torch.cat((tensor, torch.tensor([3])), dim=0)
print(out)

tensor([1, 0, 1, 1, 1, 1, 0, 0, 1, 0])
tensor([1, 2, 3])


In [7]:
# Triangular matrix 

# upper
out = torch.triu(torch.ones(3, 3))
print(out)

# lower
out = torch.tril(torch.ones(3, 3))
print(out)

tensor([[1., 1., 1.],
        [0., 1., 1.],
        [0., 0., 1.]])
tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])


In [8]:
# Masks!
out = torch.zeros(3, 3).masked_fill(torch.tril(torch.ones(3, 3)) == 0, float('-inf'))
print(out)

print(torch.exp(out))

tensor([[0., -inf, -inf],
        [0., 0., -inf],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])


In [9]:
# Transpose

input = torch.zeros(1, 2, 3)
print(input.transpose(0, 1).shape)
print(input.transpose(0, 2).shape)


torch.Size([2, 1, 3])
torch.Size([3, 2, 1])


In [10]:
# Stacked 

t1  = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.tensor([7, 8, 9])

print(torch.stack([t1, t2, t3]))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [11]:
# Linear layer? 

import torch.nn as nn


sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 2, bias=False)
print(linear(sample))

tensor([0.0813, 7.7409], grad_fn=<SqueezeBackward4>)


In [12]:
# Softmax function apply

import torch.nn.functional as F

t1 = torch.tensor([10., 50., 100.])
softmax_out = F.softmax(t1, dim=0)

print(softmax_out)

tensor([8.1940e-40, 1.9287e-22, 1.0000e+00])


In [13]:
# Embeding layer

import torch.nn as nn

vocab_size = 24
embedding_dim = vocab_size
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices = torch.LongTensor([1, 5, 3, 2])
embbeded_out= embedding(input_indices)

# this should be (4, 24). 4 for the input size, 24 for vocab_size, like a one hot encoding. 
print(embbeded_out.shape)


torch.Size([4, 24])


In [14]:
# Matrix multiplication

a = torch.tensor([[1, 2], [3, 4],[5, 6]])
b = torch.tensor(([1, 2, 3], [4, 5,6]))

c = a @ b
print(c)

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])
